### ISSUE TITLE
[第5回]　赤外線LEDの発光状態を配布したWEBカメラで確認

### ISSUE THREAD

**Issue by pshimizu** [OmeSatoFoundation/ome-doc#115]
高性能なスマホは赤外線フィルターが強力で、発光が確認できないので、
教材として配布したWEBカメラで発光しているか確認することを手順として入れたい
人の目に見えなくても本当に光っていることを知らせたい

**Comment by onitama** [comment]
赤外線リモコンの発光をWEBカメラで確認するということでしょうか?
第2回とありますが、リモコンを使用する第5回で行うのが良いかと思いますがいかがでしょうか。
