### ISSUE TITLE
第2回　オリジナルソースコードの場所をドキュメントに示す

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#117]
第2回はソースコードや画像を直接変更することが多く、それらを復元したい場合がある。
そのために作業ディレクトリである`/home/pi/02/`の他に、オリジナルのコードや画像を保存してある`/home/pi/ome/02/org/`がある。
しかし`/home/pi/ome/02/org/`についての記述がドキュメントにない。
そのため「ソースコードや画像を復元したければ`/home/pi/ome/02/org/`からコピーすればよい」という記述を教科書に追加した方がいいと思う。

**Comment by onitama** [comment]
/usr/local/share/ome/ がオリジナルになるのでその旨追加しました。
ブランチ onitama230601 にて修正しました。
https://github.com/OmeSatoFoundation/ome-doc/commit/044d1b759bebc8eca4e1d0cd4b94ebdd8097a2a6
