### ISSUE TITLE
第2回: Raspberry Pi 400のOpenHSP Editorの挙動を明記する

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#119]
Raspberry Pi 3系の場合、OpenHSP Editorでスクリプトを実行すると実行画面がフルスクリーンで表示される。
それに対してRaspberry Pi 400の場合、実行画面はウィンドウサイズで表示される。
このときスクリプトを実行している最中に、OpenHSP Editorでスクリプトを編集しようとしてもOpenHSP Editorが反応しない。
生徒が混乱するのを防ぐためにも、この仕様について教科書に明記すべき。

**Comment by onitama** [comment]
ブランチ onitama230601 にて修正しました。
https://github.com/OmeSatoFoundation/ome-doc/commit/044d1b759bebc8eca4e1d0cd4b94ebdd8097a2a6
