### ISSUE TITLE
第1回 小中学生向けの表記を使用する

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome-doc#152]
問題１：

> 図のキャプションFigureは小中学生をターゲットとしたときに表記として適切でない。
> 
> 概要：
> 現在の図用のマクロは以下のように定義されている。
> （Figureはカウンタ）
> \renewcommand\theFigure{\arabic{Figure}}
> 
> 文中では、以下のように用いられている。
> Figure \stepcounter{Figure}{\theFigure}
> 
> ・案１　マクロを変える
> \renewcommand\theFigure{図\arabic{Figure}}
> 
> ・案２　文中を変える
> 図 \stepcounter{Figure}{\theFigure}

問題２：

> 小学生に適切でない漢字が使用されている。
> 小4以降の漢字が使われている箇所をスクリプトで検出し、修正する。スクリプトkanjicheck.pyは、
> python3 kanjicheck.py  filename
> で使用する。

**Comment by twinkletia** [comment]
問題２に関しては、他のissueの進捗次第のため、最後に行うこと。

**Comment by tatsuya-hasegewa** [comment]
問題２に関しては、ルビを使用する。
