### ISSUE TITLE
Raspberry Pi 400 のキーボード配列は US

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#180]
演習で使用する Raspberry Pi 400 のキーボード配列は US 101 系 (少しキーが多いが 104 ではないコンパクト版) ですが、
初回起動時のウィザードで Language を Japanese に設定すると日本語キーボード扱いになり、
キートップの表示と入力内容に不一致が発生します。

[chap01_01.tex 290行目](https://github.com/OmeSatoFoundation/ome-doc/blob/817570adc7c939db43fedc83f4fe22dacb91608f/01/contents/chap01_01.tex#L290) にて、スクリーンショットには Use US Keyboard にチェックが入っていますが、
加えて説明文でも触れておくと親切かと思います。

**Comment by twinkletia** [comment]
承知しました。
担当の者に伝えます。

**Comment by twinkletia** [comment]
commit f9a0d1f, 74f6b24
で対応

**Comment by ip-arch** [comment]
> commit [f9a0d1f](https://github.com/OmeSatoFoundation/ome-doc/commit/f9a0d1f632d446da1578518db758a94e853d78ed), [74f6b24](https://github.com/OmeSatoFoundation/ome-doc/commit/74f6b24f98bc38cfc36a90805fe7bc2e82a5658e) で対応

図の赤枠だけでなく、本文に詳しく説明してください。
キーボードのレイアウトは、機械により異なるものがあり、未来塾では、コンピュータの専門家に多く使われている米国のUS配列というキーボードを用いるという内容を、積極的に本文中に書いておかないと、間違える子どもが出ます。

**Comment by twinkletia** [comment]
commit b2ed4aa72745693b3df0139054b600d3ed87f070
で、キーボードレイアウトについての説明が追加されました。
https://github.com/OmeSatoFoundation/ome-doc/blob/b2ed4aa72745693b3df0139054b600d3ed87f070/01/contents/chap01_01.tex#L463
