### ISSUE TITLE
【第１回】　１．１１．６表１のパスワードに使える記号が間違っている

### ISSUE THREAD

**Issue by ip-arch** [OmeSatoFoundation/ome-doc#184]
LaTeXでは<>は¡¿に変換されるので、表１に示す文字が本来の記号と異なる。

"!@#$%ˆ&*() +‘{}|[]\:”;’¡¿?,./"

**Comment by twinkletia** [comment]
commit d49317f609bdfc24f932564f41707c7214e4af00
で対応
