### ISSUE TITLE
第1回3章 GIMPでのツール選択手法

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome-doc#210]
メニューバーから描画ツールを指定する方法はPCに慣れて居ない生徒には直感的でなく、わかりづらい。
前年度までは、アイコンで表示されたものをクリックする方式であったが、今環境ではデフォルトではそのようなものが表示されていない。
アイコンで表示されたものをクリックする方式を適用する方法があれば、そちらで手順の作成をすべき。

**Comment by ip-arch** [comment]
WindowsタブのHide Docksがチェックされていませか？
これをチェックすると全てのドックが閉じます。
新しくドックを開くには、Windowsタブから開きたいドックをクリックすると、ドックが表示されます。
一番よく使うツールボックスにはショートカットが用意されていて、^Bで一発で開きます。
最後に開いた状態を記憶するには、Edit->preference->Tool optionsからsave tool options on exitをクリックしておきます。
でも、^Bだけ教えれば十分かも？

**Comment by twinkletia** [comment]
今確認しましたが、Hide Dockはチェックされていませんでした。
やはり、UIが変わってアイコンは同種ツールのうち1種しか表示されないと思われます。メニューバー以外のツール変更方法として、現在は、ツールの上で右クリックをすると同種のツールが表示されるようなので、そちらを記載しようと思います。
前UI（2022年度教科書より抜粋）
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/ff2d2b08-06be-4ff4-a5de-68582c606944)
現UI
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/14f99283-bcb2-4199-bdf5-8c9cbd7fc765)

下画像のように、ブラシの上で右クリックをすると同種ツールが表示されます
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/0cf54755-4084-4bcd-ba0b-68c30f7a6a52)
