### ISSUE TITLE
第1回テキストp.9のルビがうまく振られていない

### ISSUE THREAD

**Issue by Yoshi-Sugawara** [OmeSatoFoundation/ome-doc#223]
第1回テキストの9ページ1行目において

> 間違まちがっている

と表記されている箇所があります
申し訳ないことにルビの振り方が分からず，どなたか修正していただけないでしょうか

**Comment by twinkletia** [comment]
ご指摘ありがとうございます。commit 371d8415b7c47fe4235624ef7fab0a02712d6ed3 で修正いたしました。
