### ISSUE TITLE
[第5回] リボンケーブルの付け方についての注意書きを追記する

### ISSUE THREAD

**Issue by tikisi** [OmeSatoFoundation/ome-doc#229]
リボンケーブルの付け方についての注意書きを追記する。

**Comment by yutashx** [comment]
第3章は3.6に追記、第5章は5.2に追記する。

**Comment by RollMan** [comment]
03 回の分は、https://github.com/OmeSatoFoundation/ome-doc/pull/266 にて解決。

05 回の分は、FaBo のシールドを接続した写真を追加で撮影する必要がある。
