### ISSUE TITLE
[第5回] 図中のテキストが消えている

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#231]
期待される教科書の画像
![Screenshot from 2023-06-15 16-17-00](https://github.com/OmeSatoFoundation/ome-doc/assets/12932215/41cc46d4-040d-4124-bd63-7e1521475531)

現状の教科書の画像
![Screenshot from 2023-06-15 16-13-30](https://github.com/OmeSatoFoundation/ome-doc/assets/12932215/9fe94b20-820a-439f-8552-fa266a9562ae)

**Comment by RollMan** [comment]
めっちゃフォントの問題っぽい この図だけなにか具体的に指定したのかも

2023年6月15日(木) 16:17 yutashx ***@***.***>:
