### ISSUE TITLE
leafpad は mousepad に変更された

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#234]
講義で使用していた leafpad は mousepad というふうにコマンド名 (もしかすると実態も) が変わったため，
教科書通りの方法ではテキストエディタを使用できない．

leafpad はパッケージレポジトリからもなくなったため，(ビルドはせず) 教科書の指定を mousepad に変更する．

**Comment by yutashx** [comment]
close #260
