### ISSUE TITLE
第7回　ドキュメントルートの説明が足りてない

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome-doc#240]
2022年度第7回29p、ドキュメントルートの説明が「サーバから見たルートディレクトリ」というあっさりとした説明となっている。第7回までの教科書で、「ルート」の検索結果は0件であり、2023年度第3回でのディレクトリ階層構造の説明(3.3.2)では、ルートディレクトリを「一番上のディレクトリ」と説明している。そのため、第7回でいきなりルートディレクトリという単語が出てきて生徒がすぐ理解できるとは思えない。

**Comment by tikisi** [comment]
- ルートディレクトリが何か伝わるか？=> 第3回で説明していることを追記する
- サーバーだと曖昧なので、ウェブサーバーにする
- 「ファイルシステムのルートディレクトリ」と「ウェブサーバーのルートディレクトリ」が異なることを追記する
  - `webserver.py`では、それを起動したディレクトリがルートディレクトリになる
