### ISSUE TITLE
第7回　迷惑メールの例が適切でない

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome-doc#243]
3p 「迷惑メールは見ない、送らない」の項目で、具体例としてチェーンメール(呪いのメール)などと書いてあるが、今の小中学生に向けた具体例としてふさわしくないと感じる。

**Comment by tikisi** [comment]
チェーンメールの説明を追加して対応する
```
メール本文中に、『誰かに回して』 『○○人に転送するように』などと書かれているメールを受け取ったのなら、それはどんな内容でもチェーンメールです。
```

https://www.dekyo.or.jp/soudan/chain/
