### ISSUE TITLE
tar --recursive-unlinkのハイフンが1つに見える

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome-doc#293]
https://github.com/OmeSatoFoundation/ome-doc/blob/5b819a1c1206df1147583046d5d0296f016c86a9/03/contents/chap03_02_2_14.tex#L23
15ページの--recursive-unlinkオプションが教科書だとつながっていて、私にはハイフン1つに見えました。（紙に印刷してみても同じでしたが、私の印刷環境が本番と同じである確証はありません）
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/9de0dd7c-c750-4082-b731-eb913eb6fd0c)

**Comment by RollMan** [comment]
en dash として解釈されてると思いますので、修正が必要ですね。結局 inline verbatim のようなものが必要そうです。

**Comment by hogenimushi** [comment]
見た目が少し変わりますが、表題のハイフン２つを\verbで囲いました。
