### ISSUE TITLE
問題3-9 文言の追加を提案します

### ISSUE THREAD

**Issue by hirohaku21** [OmeSatoFoundation/ome-doc#296]
問題3-9 文言の追加を提案します。

1. cdと入力してホームディレクトリに移動しましょう。
mousepad my.txt & と入力してみましょう。マウスパッドが開きます。　……

例題コマンドの状態と問題を解いている時の状態が不一致になります。問題を解くための誘導ができないおそれがあります。

問題3-8でrikaディレクトリに入った状態です。
問題3-9は 3.4.7の例題コマンドを見るとホームディレクトリにいます。

**Comment by hogenimushi** [comment]
それでは、「ホームディレクトリに移動しましょう。」を追加してみますね。あえて指示を曖昧にすることで理解度が測れるかと思います。

**Comment by hirohaku21** [comment]
良いと思います⭕️
