### ISSUE TITLE
問題3-17 文言の訂正を提案します

### ISSUE THREAD

**Issue by hirohaku21** [OmeSatoFoundation/ome-doc#298]
問題3-17 文言の訂正を提案します。

1. ボタンの状態を調べる命令を書きましょう。

元は　「ボタンが押されているか」だと、答えは16.17行目の2行を回答しなくてはならず、回答者が困惑します。
誘導するために、リスト3.24 の16行目のコメントと合わせるべきだとか考えています。

**Comment by hogenimushi** [comment]
良いと思います。修正しました。
