### ISSUE TITLE
問題3-13-2　 回答欄の誤り（記述式→チェック式）

### ISSUE THREAD

**Issue by yuukiner** [OmeSatoFoundation/ome-doc#309]
問題3-13　2. 回答欄誤りを報告します。

2.　カレントディレクトリの中身を見てみましょう見てみましょう、という問題に対して、
答え.　と記述式の回答欄になっているため、何を書けばよいのかわからず混乱してしまう。

□　←できたらチェックしましょう　（チェック方式）への変更を提案します。

**Comment by Rio-211** [comment]
すでに修正してあるみたいです

**Comment by RollMan** [comment]
Completed at #300
