### ISSUE TITLE
3.9.3　剰余算の説明文について

### ISSUE THREAD

**Issue by yuukiner** [OmeSatoFoundation/ome-doc#310]
小5の生徒が先生の説明を聞いていた際に、1÷4は0余り1　という説明を聞いて、0？と質問をしてきました。普段使っているひっ算と違い、バックスラッシュなどの記号が出てくることで、簡単な計算であっても頭の中ですぐに計算式が結びつかなかったようです。ホワイトボードで先生が順を追って説明していくと、リズムよく感じて理解ができていたようなので、後から見返して理解を定着させるために、教科書へ反映させることを提案します。（計算式のリスト部分は正式な書き方があれば訂正したうえでの反映をお願いします）

＜現状＞
例えば、 5 \ 4 は 5 を 4 で割った余りである 1 になります。
ledidx = (ledidx+1) \ 4 では、何回 *hata まで戻っているか数えています。 LED は 4 つあるので、4 回動けば一周できます。一周したらまた 0 に戻りたいので、剰余算を使っています。今回は ledidx は 0～3 のどれかの数字になります。

＜提案＞
例えば、 5 \ 4 は 5 を 4 で割った余りである 1 になります。
ledidx = (ledidx+1) \ 4 では、何回 *hata まで戻っているか数えています。 LED は 4 つあるので、4 回動けば一周できます。一周したらまた 0 に戻りたいので、剰余算を使っています。今回は ledidx は 0～3 のどれかの数字になります。　<---ここまで同じ
実際に計算すると、次のようになりますね。　　　　　　　　<---ここから追加
　・ledidxが0のとき = (0+1) \ 4 　答えは0 余り1　→ledidxは1になる
　・ledidxが1のとき = (1+1) \ 4 　答えは0 余り2　→ledidxは2になる
　・ledidxが2のとき = (2+1) \ 4 　答えは0 余り3　→ledidxは3になる
　・ledidxが3のとき = (3+1) \ 4 　答えは1 余り0　→ledidxは0になる
このように剰余算をうまくつかうことで、4つのLEDの切り替えを実現しています。

**Comment by hogenimushi** [comment]
プログラムには静的な側面と動的な側面がありますので、それを教科書に書いておくのはとても良いと思いました。
以下のように変えてみましたがいかがでしょうか。

![image](https://github.com/OmeSatoFoundation/ome-doc/assets/9530414/1a3546f5-af5a-4ca9-a640-84f8591fcb15)

**Comment by yuukiner** [comment]
実際に計算すると、次のようになります以降の変数名に誤記がみられます。
（ledidx と書くべきところが、 ledid となっている×4カ所）
それ以外は問題なく、これが良いと思います。
