### ISSUE TITLE
相対パスのフリガナ、rootの記載　を追加

### ISSUE THREAD

**Issue by yuukiner** [OmeSatoFoundation/ome-doc#311]
講義で一番話が長くなるところなので、生徒によっては話を聞いていません。
後から教科書を見直した際に必要な情報として、以下の追加を提案します。

①相対パスのフリガナ
②rootの記載、読み方
　現状：　一番上のディレクトリは / スラッシュで書きます。
　提案：　一番上のディレクトリは / スラッシュで書きます。特別なディレクトリで、root（ルート）と呼びます。

**Comment by hogenimushi** [comment]
ご指摘ありがとうございます。以下のように変えてみました。
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/9530414/a6ea46b1-d601-496c-873f-4dcb6becaab2)
