### ISSUE TITLE
カレントディレクトリを確認する癖をつける

### ISSUE THREAD

**Issue by yuukiner** [OmeSatoFoundation/ome-doc#313]
子どもたちがカレントディレクトリを確認する癖をつけるため、また手を動かす機会を増やすために、問題文の変更を提案します。

＜問題3-4＞

-1. cd␣Pictures/と入力して Pictures ディレクトリに移動してみましょう。
↓
-1.cd␣Pictures/と入力して Pictures ディレクトリに移動し、pwd コマンドでカレントディレクトリを確認してみましょう。

-2. cd と入力してホームディレクトリに移動してみましょう。
↓
-2. cd と入力してホームディレクトリに移動し、pwd コマンドでカレントディレクトリを確認してみましょう。

**Comment by hogenimushi** [comment]
#312 を修正しているときに、私もそちらの方が良いと思い一緒に直しました。
