### ISSUE TITLE
[第5回] 「自動車に使われているセンサー」のイラストをスマホなど、分かりやすいものに変える

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#327]
# 概要
センサーが使われている身近なプロダクトとして、自動車よりスマホの方が良いのではないかという話が挙がった。
そこで子供がより身近で分かりやすいイラスト及び文章を検討する必要がある

**Comment by Rio-211** [comment]
スマートフォンの画像の候補を出します
https://publicdomainq.net/smartphone-mobile-phone-0003712/

**Comment by Rio-211** [comment]
- スマートフォンに使われているセンサーを探して、センサーを搭載した目的と使用用途についてまとめました
- これらをベースにセンサーのイラストを作成していきます

### スマホについているセンサー一覧
- GPSセンサー
   - 正確な位置を割り出すために使われている
   - マップアプリなどに使われている
- 磁気センサー
   - 磁力を検知して方角を示すために使われている
   - 電子コンパスなどに使われている
- 加速度センサー
   - スマートフォンの向きを検知するために使われている
   - スマートフォンの画面を回転させることなどに使われている
- ジャイロセンサー
   - スマートフォンの回転スピードを検知するために使われている
- 環境光センサー
   - 周囲の明るさを検知するために使われている
   - スマートフォンの明るさの自動調節などに使われている
- 近接センサー
   - 近づいてくるものを検知するために使われている
   - 通話するときに画面を暗くすることなどに使われている
- 指紋センサー
   - 指紋パターンを検知するために使われている
   - 指紋認証などに使われている

[スマートフォンで搭載されているセンサー類と役割まとめ](https://garumax.com/smartphone-sensor)より
