### ISSUE TITLE
[第二回]「〜する必要がある」の表現について

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#33]
In GitLab by @ayanoaizu on Nov 30, 2019, 21:53

「〜する必要がある」という表現よりも、「〜します」といった簡易な表現のほうが小学生がわかりやすい...?

**Comment by onitama** [comment]
ブランチ onitama230605 にて修正しました。
https://github.com/OmeSatoFoundation/ome-doc/commit/fd2dfa83199ab07ef98f12574c55cb9bc4fc6a66
