### ISSUE TITLE
[第二回]コメントの説明について

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#34]
In GitLab by @ayanoaizu on Nov 30, 2019, 21:54

第二回P.21例題2-6答え
color 0,0,0;←黒
とあるが、hspのコメントアウトについて説明がないので説明をする

**Comment by onitama** [comment]
ブランチ onitama230605 にて修正しました。
https://github.com/OmeSatoFoundation/ome-doc/commit/078446d2bb8038d8509c2179828aea7fa1534281
