### ISSUE TITLE
[第6回]　誤字、フォーマット修正

### ISSUE THREAD

**Issue by sugasin2813** [OmeSatoFoundation/ome-doc#341]
- [x] 6.1.1, p1. 05 -> 06
- [x] 6.6, p8 sertvoice -> setvoice
- [x] 問題6-8. 一つ目の問題のチェックボックスの下のスペースが無い。
- [x] 6.11, p16. leafpad -> mousepad
- [x] 6.13, リスト6.8 \textasciitildeが~になっていない

**Comment by hogenimushi** [comment]
「問題6-8. 一つ目の問題のチェックボックスの下のスペースが無い。」は、latexの仕様で改ページを防ぐために不要と判断されたスペースがつぶれたのではないかと思います。「6.13, リスト6.8 \textasciitildeが~になっていない」は、もともとHSPで~を展開してくれないため、カレントディレクトリのファイルを読むようにし、記述を外しました。ここでのファイル指定は絶対パスで行わなければならない旨の記述を加えました。
#346
