### ISSUE TITLE
第7，8回 ~/ome/0x -> ~/0x

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome-doc#349]
**テキスト・画像の修正を行う必要あり。**

- 第７回要修正画像(07/text07-img/ome7-imgXXX)
033, 034, 038
- 第８回要修正画像(08/text08-img/textbook-imgXXX)
002\~006, 015, 020, 022, 031, 032, 032-1, 032-2, 057, 063\~066

**Comment by twinkletia** [comment]
- 第７回要修正画像
033, 034, 038
- 第８回要修正画像
002~006, 015, 020, 022, 031, 032, 032-1, 032-2, 057, 063~066

**Comment by TaitoUeda** [comment]
該当箇所の変更が不完全
