### ISSUE TITLE
[第二回]第一回との整合性について

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#35]
In GitLab by @ayanoaizu on Nov 30, 2019, 21:57

第一回では、画像をGIMPを使って加工するときに、
1. 画像のあるディレクトリに移動
2. 画像を選択して右クリック
3. GIMPを選択して開く
といった手順を取っているが、
第二回では
1. GIMPを開く
2. ファイル→開く→画像選択
の手順を取っている。

どちらかの手順に統一するorどちらでも大丈夫という説明を追加する

**Comment by onitama** [comment]
第1回の形に合わせました。
ブランチ onitama230605 にて修正しました。
https://github.com/OmeSatoFoundation/ome-doc/commit/9ca66c0581505f5f31152ddf9725fb75780790e4
