### ISSUE TITLE
[第5回] digin.hspでボタンを押した時に光るLEDをセンサーボードのLEDからFaboのLEDに変更する

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#355]
現状、digin.hspでボタンを押した時に光るLEDは、GPIO 17のLED、つまりセンサーボードのLEDを指定している。
そのため、digin.hspを実行する直前に接続したGPIO 23のLEDであるFaboのLEDに変更する。

**Comment by sugasin2813** [comment]
hspのledの番号を17から23へ変更する
