### ISSUE TITLE
［第6回］リスト6.8 文字訂正

### ISSUE THREAD

**Issue by hirohaku21** [OmeSatoFoundation/ome-doc#358]
誤　リスト6.8  ledvoice.hsp
正　リスト6.8  led**by**voice.hsp
ご訂正の方をよろしくおねがいします。

**Comment by AizuKnight** [comment]
リスト6.8のcaptionが`ledvoice.hsp`となっていたのを`ledbyvoice.hsp`と修正した。Pull Requestは作成済み。
