### ISSUE TITLE
[第二回]説明がわかりにくい

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#36]
In GitLab by @ayanoaizu on Nov 30, 2019, 22:00

第二回P.26
「GIMPアプリケーションを閉じるのを忘れないでください（koma.pngを保存してあるので、現在のドキュメントを保存する必要はありません）」の説明がわかりにくい。

- [ ] 第一回ではGIMPを閉じる指示はなかったのにここで閉じる理由が知りたい。
- [ ] 「現在のドキュメント」とは何？
- [ ] なぜ保存する必要はないのか？

**Comment by onitama** [comment]
ブランチ onitama230605 にて表現を修正しました。
第一回でもエクスポートで保存しているので、どこかでアプリケーションを閉じないと警告されてしまう気がします。
https://github.com/OmeSatoFoundation/ome-doc/commit/313637f9751d1a8dcfbf1df31f90a11af944f443
