### ISSUE TITLE
[第7回] 自己紹介ページの画像のコピー忘れ

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#363]
例題7-4で、第1回の講義で使用した`self_intro.html`を`~/07/www/index.html`にコピーするという記述がある。
このとき、第1回の`self_intro.html`が参照している画像をコピーしていないため、第7回の`index.html`を表示すると、画像が表示されない。

そのため、例題7-4の`self_intro.html`をコピーする際に画像もコピーする記述を入れたほうが良いのではないか。

**Comment by TaitoUeda** [comment]
リネームせずに変更、フェイス以外にも使っているものがあれば変更してくださいの表記を追加する。

**Comment by TaitoUeda** [comment]
コマンドラインの追加
