### ISSUE TITLE
[第7回] センサーボードを接続する記述がない

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#365]
例題7-7の「CGI を使ってウェブページから LED をつける」では、Raspberry Piにセンサーボードを取り付ける必要がある。しかし、例題7-7では、センサーボードを取り付ける必要がある旨の記述がない。
そのため、センサーボードを接続する必要があるという内容の記述を追加したほうが親切である。

**Comment by TaitoUeda** [comment]
ラズパイの表記に統一する
