### ISSUE TITLE
[第7回]　表記ゆれ及び表記ミス

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#368]
文章内でいくつかの単語に表記ゆれ及び表記ミスがあったので、列挙する。

表記ゆれ
- webとWEB
- ラズベリーパイ1号機とラズベリーパイ一号機

表記ミス（修正しなくてもいいかも）
- google → Google
- wifi → Wi-Fi

**Comment by TaitoUeda** [comment]
p13 p32　などにおいて表記変更が未完了
