### ISSUE TITLE
[第7回]　違和感がある本文

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#369]
本文中にいくつか違和感のある文章があった。
1.  「 文字の種類によっては見えなかったり最悪の場合ネットワークが見られないことも考えられます。」の文章が分かりづらい
https://github.com/OmeSatoFoundation/ome-doc/blob/cc4a80082f5d4058f3496b9c037cffc0a744d0b6/07/text07.tex#L146 
2. 「\ \ みなさんが作ったindex.htmlの場所はwebserver.pyを起動したディレクトリと同じで\ \ したね。」の「同じで」の後に不要な空白がある。
https://github.com/OmeSatoFoundation/ome-doc/blob/cc4a80082f5d4058f3496b9c037cffc0a744d0b6/07/text07.tex#L1178

改善案
1. 次のように変更する「文字の種類によっては見えなかったりすることがあります。」
2.  `\ \ `を削除する

**Comment by hogenimushi** [comment]
ネットワークを使っている人たちはみんな同じものを使っているとは限りません。使っている機種が、PCだったり、スマートフォンだったり、ラズベリーパイだったりします。機種によっては、絵文字や特殊文字が見えなくなることが考えられます。
