### ISSUE TITLE
[第二回]プログラムの書き換えで行を指定するのをやめる

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#37]
In GitLab by @ayanoaizu on Nov 30, 2019, 22:05

第二回P.26「106行目にある〜」
テキスト指定のエディタだと行数がわからないので、だいたいプログラムのどこにあるのか指示する。
106行目はプログラムのほぼ真ん中あたりにあります。

**Comment by onitama** [comment]
ブランチ onitama230605 にて修正しました。
https://github.com/OmeSatoFoundation/ome-doc/commit/912dbc246e059f7b4b500521b3bdf8562888e231
