### ISSUE TITLE
[第7回] `host`コマンドが動かない

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#370]
`host`コマンドを動かしたところ、`libdns-9.16.27-Debian.so`が見つからないと言われた。

```
yutashx@raspberrypi:~ $ host amazon.co.jp
host: error while loading shared libraries: libdns-9.16.27-Debian.so: cannot open shared object file: No such file or directory
```

類似のコマンドの`dig`は正常に動いた。

![2023-08-24-160759_1920x1080_scrot](https://github.com/OmeSatoFoundation/ome-doc/assets/12932215/57c95d73-fa71-4ec9-9280-680c5c53576d)

**Comment by tikisi** [comment]
hostコマンドをdigで置き換えて対応する。

**Comment by TaitoUeda** [comment]
hostコマンドの変更に伴い画像内の冗長な説明について変更する。
