### ISSUE TITLE
[第8回] `ascii_table.html`が見つからない

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#373]
`links.html`に含まれているASCIIコード表のリンク先の`ascii_table.html`が第8回の演習用のディレクトリ`~/08`下で見つからない。

**Comment by ip-arch** [comment]
これは、08/wwwの下にあります。
www下でサーバーを動かせば、ascii_table.htmlは見えるはずなのですが、教科書通りに動かして404になりましたか？

**Comment by tikisi** [comment]
このままで問題なさそうなので、実機で再度確認する。

**Comment by twinkletia** [comment]
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/19b8e5cd-e382-44d7-b5d4-a3cbc16c0483)

![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/8489b8ab-dd10-4791-af07-aa1029c27050)
![image](https://github.com/OmeSatoFoundation/ome-doc/assets/78594153/1934dd95-3d59-4889-b41d-63e485fa3115)

links.htmlはテキスト内でこのように使われていて、サーバ稼働下で動くことを想定されていないと思われます。
そのため、リンク先を./ascii_table.htmlから./www/ascii_table.htmlにするPRを出しました。

**Comment by ip-arch** [comment]
ome2023の変更によりome-doc側のissueはクロースする
