### ISSUE TITLE
[第7回] 図にPower Pointのセレクタが誤って載っている

### ISSUE THREAD

**Issue by yutashx** [OmeSatoFoundation/ome-doc#433]
第7回のP16の図に、PowerPointのセレクタが誤って載っているので、修正した方がよい。

**Comment by NetworkDesignLab** [comment]
該当する画像である"ome7-img024"の拡張子(.png)が消えていて修正することができない状態です。

**Comment by RollMan** [comment]
古いリポジトリ ( adaptive.u-aizu.ac.jp/gitlab ) よりソースの EPS ファイルだけ見つけましたので、ご活用ください。

[ome7-img006.zip](https://github.com/OmeSatoFoundation/ome-doc/files/15376401/ome7-img006.zip) (esp を添付できなかったので zip でくるみました。解凍してください)

中身は一見 PNG かと思いましたが、PNG としては開けませんでした。

![image](https://github.com/OmeSatoFoundation/ome-doc/assets/3908541/90d7cc0b-73ce-463b-bc3b-c61862247958)

**Comment by RollMan** [comment]
古いリポジトリ ( adaptive.u-aizu.ac.jp/gitlab ) よりソースの EPS ファイルだけ見つけましたので、ご活用ください。

[ome7-img024.zip](https://github.com/OmeSatoFoundation/ome-doc/files/15376456/ome7-img024.zip)

**Comment by RollMan** [comment]
```
$ file ome7-img027
ome7-img027: StarView MetaFile, version 256, size 822083584
```

**Comment by RollMan** [comment]
画像のソースがあると思われる以前のバージョンのリポジトリを共有しました (internal link: https://omesato.hogenimushi.jp/main/pl/kdq8kx6hotgbxx73h6ywfpcfqw).

**Comment by NetworkDesignLab** [comment]
リポジトリの共有ありがとうございます。
.epsの画像があり編集できました。助かりました。
