### ISSUE TITLE
外付けBME280をraspberry pi 上に置いて動作するか確認する

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome-doc#79]
In GitLab by @yshimmyo on Sep 11, 2021, 18:17

BME280のGNDとVinがむき出しになっているため、センサーボード上のハンダやUSBの金属部分に接触してショートすることがある。
注意を促す必要がある．

https://adaptive.u-aizu.ac.jp/gitlab/ome/ome2019/issues/62

**Comment by sugasin2813** [comment]
教科書中に注意書きがされているかどうかを確認する。
もしされていなければ追記する
